/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementEditor: typeof import('./../components/admin/AnnouncementEditor.vue')['default']
    CheckInOut: typeof import('./../components/student/CheckInOut.vue')['default']
    DistributionPie: typeof import('./../components/common/charts/DistributionPie.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmptyState: typeof import('./../components/common/UI/EmptyState.vue')['default']
    Footer: typeof import('./../components/common/Layout/Footer.vue')['default']
    Header: typeof import('./../components/common/Layout/Header.vue')['default']
    HeatMap: typeof import('./../components/common/charts/HeatMap.vue')['default']
    Loading: typeof import('./../components/common/UI/Loading.vue')['default']
    MyReservations: typeof import('./../components/student/MyReservations.vue')['default']
    ReservationForm: typeof import('./../components/student/ReservationForm.vue')['default']
    RoomCard: typeof import('./../components/common/UI/RoomCard.vue')['default']
    RoomList: typeof import('./../components/student/RoomList.vue')['default']
    RoomManager: typeof import('./../components/admin/RoomManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeatItem: typeof import('./../components/common/UI/SeatItem.vue')['default']
    SeatLayoutEditor: typeof import('./../components/admin/SeatLayoutEditor.vue')['default']
    SeatMao: typeof import('./../components/student/SeatMao.vue')['default']
    Sidebar: typeof import('./../components/common/Layout/Sidebar.vue')['default']
    StatisticsDashboard: typeof import('./../components/admin/StatisticsDashboard.vue')['default']
    TrendLine: typeof import('./../components/common/charts/TrendLine.vue')['default']
    UsageBarChart: typeof import('./../components/common/charts/UsageBarChart.vue')['default']
    UserManager: typeof import('./../components/admin/UserManager.vue')['default']
  }
}
